USE ROLE SYSADMIN;

-- Create a database for experimentation
CREATE OR REPLACE DATABASE ANOM_DETX;
CREATE OR REPLACE SCHEMA ANOM_DETX.AD_LABS;

-- Create a specific warehouse for ML/AI workloads (Standard or Medium recommended for ML)
CREATE OR REPLACE WAREHOUSE ANOM_DETX_WH WITH
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 60;

USE WAREHOUSE ANOM_DETX_WH;
USE SCHEMA ANOM_DETX.AD_LABS;
