USE WAREHOUSE ANOM_DETX_WH;
USE SCHEMA ANOM_DETX.AD_LABS;

ALTER TABLE LAB_CALL_CENTER_KM
ADD COLUMN IF NOT EXISTS DATASET_SPLIT STRING;


-- Label each row as TRAIN / TEST / PROD

UPDATE LAB_CALL_CENTER_KM
SET DATASET_SPLIT =
    CASE
        WHEN CALL_DATE < '2024-09-01' THEN 'TRAIN'            -- Jan–Aug
        WHEN CALL_DATE < '2024-11-01' THEN 'TEST'             -- Sep–Oct
        ELSE 'PROD'                                           -- Nov–Dec
    END;

-- Create physical tables from the split 
CREATE OR REPLACE TABLE LAB_CALL_CENTER_KM_TRAIN AS
SELECT *
FROM LAB_CALL_CENTER_KM
WHERE DATASET_SPLIT = 'TRAIN';

CREATE OR REPLACE TABLE LAB_CALL_CENTER_KM_TEST AS
SELECT *
FROM LAB_CALL_CENTER_KM
WHERE DATASET_SPLIT = 'TEST';

CREATE OR REPLACE TABLE LAB_CALL_CENTER_KM_PROD AS
SELECT *
FROM LAB_CALL_CENTER_KM
WHERE DATASET_SPLIT = 'PROD';


-- Quick checks (counts + anomaly distribution)
-- Row counts by split
SELECT DATASET_SPLIT, COUNT(*) AS ROWS_COUNT
FROM LAB_CALL_CENTER_KM
GROUP BY DATASET_SPLIT;

-- Check ExtremeLongHandleTime distribution per split
SELECT 
    DATASET_SPLIT,
    ANOMALY_REASON,
    COUNT(*) AS ROWS_COUNT,
    ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (PARTITION BY DATASET_SPLIT), 2) AS PCT_IN_SPLIT
FROM LAB_CALL_CENTER_KM
GROUP BY DATASET_SPLIT, ANOMALY_REASON
ORDER BY DATASET_SPLIT, ANOMALY_REASON;
